#!/usr/bin/python
import pylab as py
import math
numberOfShares= float(raw_input("Number of shares: "))
price = float(raw_input("Share Price: "))
buyCost = (numberOfShares * price) + 7.95
print " To purchase %d shares , the intial investment cost is %.f" % (numberOfShares,buyCost)
for sellPrice in py.frange (price,2*price,.10):
	priceChange = sellPrice - price
	percentageChange = (priceChange / price) * 100
	sellProfit = ((numberOfShares * sellPrice) - 7.95) - buyCost
	print " If price goes up +%.2f ( %% %.2f) (%.2f) , you would make %.2f" % (priceChange,percentageChange,sellPrice,sellProfit)  

